# -*- coding: utf-8 -*-
"""data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sy2XJkEg8ylXfz92DC0_U8sReAPOy63E
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()
filename = list(uploaded.keys())[0]

df = pd.read_csv(filename)

df=df.drop(columns = "Unnamed: 0")
df=df.drop(columns = "review_author")
df=df.drop(columns = "review_bestRating")
df=df.drop(columns = "review_worstRating")
df=df.drop(columns = "rating_overall")
df=df.drop(columns = "work_details")

df['rating_promotions'].replace('-','1.0',inplace=True)
df['rating_skilldev'].replace('-','1.0',inplace=True)
df['rating_culture'].replace('-','1.0',inplace=True)
df['rating_worksatis'].replace('-','1.0',inplace=True)
df['rating_salarybenifits'].replace('-','1.0',inplace=True)
df['rating_jobsecurity'].replace('-','1.0',inplace=True)
df['rating_worklifebal'].replace('-','1.0',inplace=True)
df['rating_promotions']=df['rating_promotions'].astype(float)
df['rating_skilldev']=df['rating_skilldev'].astype(float)
df['rating_culture']=df['rating_culture'].astype(float)
df['rating_worksatis']=df['rating_worksatis'].astype(float)
df['rating_salarybenifits']=df['rating_salarybenifits'].astype(float)
df['rating_jobsecurity']=df['rating_jobsecurity'].astype(float)
df['rating_worklifebal']=df['rating_worklifebal'].astype(float)
df.info()

df.to_csv('jio-final-data.csv', index=False)
files.download('jio-final-data.csv')